"use client";
import './globals.css'
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { EthereumClient, w3mConnectors, w3mProvider } from '@web3modal/ethereum'
import { Web3Modal } from '@web3modal/react'
import { configureChains, createConfig, WagmiConfig } from 'wagmi'
import { goerli } from 'wagmi/chains'
import dynamic from 'next/dynamic'
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const chains = [goerli]
const projectId = '3aad51954bc9beedced7e487b5802f04'
const Header = dynamic(() => import('@/components/Header'), { ssr: false })

const { publicClient } = configureChains(chains, [w3mProvider({ projectId })])
const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: w3mConnectors({ projectId, chains }),
  publicClient
})
const ethereumClient = new EthereumClient(wagmiConfig, chains)

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export default function RootLayout({
  children,
}: {
  children: any
}) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <WagmiConfig config={wagmiConfig}>
          <Header/>
          <Web3Modal projectId={projectId} ethereumClient={ethereumClient} />
          {children}
          <Footer/>
        <Web3Modal projectId={projectId} ethereumClient={ethereumClient} />
        </WagmiConfig>
        <ToastContainer/>
        </body>
    </html>
  )
}
